version: '3'

services:
  redis:
    image: redis:5
    container_name: iwbuy_service_redis
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: iwbuy_service
    volumes:
      - .:/iwbuy_service
    ports:
      - "8000:8000"
    depends_on:
      - redis